### ISSUE TITLE
Unable to cross-compile to macos from linux

### ISSUE THREAD

**Issue by tiepettersen** [astonbitecode/j4rs#13] opened 2020-01-10 12:17 UTC
I've made a Docker image (Linux) to cross-compile my Rust project to macOS targets (x86_64-apple-darwin). For that I'm using [osxcross](https://github.com/tpoechtrager/osxcross) as the cross-compiler.
However, I'm getting the following error when building my project:

```
   Compiling j4rs v0.11.0
error: failed to run custom build command for `j4rs v0.11.0`

Caused by:
  process didn't exit successfully: `/project/target/release/build/j4rs-9e299e02ed1913c3/build-script-build` (exit code: 1)
--- stderr
Error: J4rsBuildError { description: "JavaLocatorError { description: \"Command \\\'/usr/libexec/java_home\\\' is not found in the system PATH (entity not found)\" }" }
```

I took a quick look into the build script, and it seems like it will conditionally look for the dynamic jvm library if `target_os` is macOS, however, this fails since the actual host is not a macOS architecture.

```rust
    } else if target_os == "macos" {
        let ld_library_path = java_locator::locate_jvm_dyn_library()?;
        let ld = env::var("DYLD_LIBRARY_PATH").unwrap_or("".to_string());
        println!("cargo:rustc-env=DYLD_LIBRARY_PATH={}:{}", ld_library_path, ld);
        println!("cargo:rustc-link-search={}", ld_library_path);
    }
```

I've also tried to comment out this if clause, however, then it tries to link to the jvm library during linking. 

```
   Compiling j4rs v0.11.0
error: linking with `x86_64-apple-darwin14-clang` failed: exit code: 1
  |
  = note: ... linker flags omitted ...
  = note: ld: library not found for -ljvm
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `j4rs`.

To learn more, run the command again with --verbose.
```

I understand if this is not tested nor the scope of this project, but I wonder if you have any idea how I could solve this?

BTW, cross-compiling j4rs for linux and windows using Docker works nicely.

**Comment by astonbitecode** [comment] 2020-01-11 23:12
AFAIK the jdk [directory structure]( https://docs.oracle.com/en/java/javase/12/install/installed-directory-structure-jdk.html#GUID-F7178F2F-DC92-47E9-8062-CA6B2612D350) in macos is a bit strange and moreover, they don't use symbolic links like in linux. Which jdk and which version do you use?

You can try exporting the `JAVA_HOME` before building. This should help.

**Comment by tiepettersen** [comment] 2020-01-15 08:48
Some progress. I exported `JAVA_HOME` and I now get the following error:

```bash
Compiling j4rs v0.11.0
error: linking with `x86_64-apple-darwin14-clang` failed: exit code: 1
  |
  = note: ... all linker flags omitted ...
  = note: ld: warning: ignoring file /usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so
          Undefined symbols for architecture x86_64:
            "_JNI_CreateJavaVM", referenced from:
                j4rs::api_tweaks::macos::create_java_vm::hf44704b4d1014646 in j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.14.rcgu.o
            "_JNI_GetCreatedJavaVMs", referenced from:
                j4rs::api_tweaks::macos::get_created_java_vms::h75043fd84c68f723 in j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.14.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `j4rs`.
```

I suppose it's throwing a fit because I'm trying to cross compile for the x86_64-apple-darwin target, however, j4rs is trying to link with the JVM installed on the host (or rather the one I'm exporting `JAVA_HOME` to). 

What I don't understand is why the macos target needs to link to statically link to JVM lib, while windows and linux target doesn't require this (I believe).

**Comment by astonbitecode** [comment] 2020-01-15 09:18
The latest behavior is because of this stale piece of code that you mentioned in the `build.rs`.

Can you try to comment this out:
```rust
else if target_os == "macos" {
        let ld_library_path = java_locator::locate_jvm_dyn_library()?;
        let ld = env::var("DYLD_LIBRARY_PATH").unwrap_or("".to_string());
        println!("cargo:rustc-env=DYLD_LIBRARY_PATH={}:{}", ld_library_path, ld);
        println!("cargo:rustc-link-search={}", ld_library_path);
    }
```

and try again? 

I suppose it is not needed any more.

**Comment by tiepettersen** [comment] 2020-01-15 09:25
I commented it out, but it still tries to link to jvm. I'm actually not sure which crate, if it's j4rs or not, that is linking libjvm.

Here's the full error:

```bash
   Compiling j4rs v0.11.0
error: linking with `x86_64-apple-darwin14-clang` failed: exit code: 1
  |
  = note: "x86_64-apple-darwin14-clang" "-m64" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.0.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.1.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.10.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.11.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.12.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.13.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.14.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.15.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.2.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.3.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.4.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.5.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.6.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.7.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.8.rcgu.o" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.j4rs.42jeedpa-cgu.9.rcgu.o" "-o" "/project/target/x86_64-apple-darwin/debug/deps/libj4rs-d32be032c6066016.dylib" "-Wl,-exported_symbols_list,/tmp/rustcExQui7/list" "/project/target/x86_64-apple-darwin/debug/deps/j4rs-d32be032c6066016.1xgtbqnc5n7c1or6.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/project/target/x86_64-apple-darwin/debug/deps" "-L" "/project/target/debug/deps" "-L" "/project/target/x86_64-apple-darwin/debug/build/libloading-d0342eab4e8a7f22/out" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib" "-ljvm" "/project/target/x86_64-apple-darwin/debug/deps/libcesu8-d501ec58c3cc1aa5.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libfs_extra-d2cd256c0e7ee3e5.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libserde_json-e0c9a90c63b0ea0a.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libryu-49b6e4c2a8fc33d0.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libitoa-1098049ec15b6a65.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libserde-3d55f60f55a967fb.rlib" "/project/target/x86_64-apple-darwin/debug/deps/liblog-03a1c192cb3e78f2.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libcfg_if-f2a0ad11de21757c.rlib" "/project/target/x86_64-apple-darwin/debug/deps/liblibc-771af09464a7db7b.rlib" "/project/target/x86_64-apple-darwin/debug/deps/liblazy_static-e157a8b13bb3c2bb.rlib" "/project/target/x86_64-apple-darwin/debug/deps/libjni_sys-e93fcc9acc8f4b45.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libstd-dc44f9d83fdd9d6a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-bf77646b97e30fab.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-0cdae3a9ab61fffa.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-8f6af59515504fce.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-3ce4ff4f5f9747ad.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-900bb8831b14a64b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-13d9189231cf7059.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libunwind-a2cbc799550e64b6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-f1aad9cf7e690e9e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/liblibc-125e8fdae26f6ee0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/liballoc-d0fc27c8cd3218b0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-79e0a0ad580533d5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libcore-da51aa61852252ac.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-fcb7ecdfe47da10c.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-dynamiclib" "-Wl,-dylib"
  = note: ld: library not found for -ljvm
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `j4rs`.
```

You can see that jvm is linked (`-ljvm`) in the middle of the linker flags.

**Comment by astonbitecode** [comment] 2020-01-15 11:02
Cross compilation beauties... [j4rs links to jvm for macos](https://github.com/astonbitecode/j4rs/blob/d4a957e95545a6eb8554d76035db64ea5609d7f1/rust/src/api_tweaks/macos.rs#L28)! 

I had forgotten about it since I don't own a mac and it got out of my attention. 
I will need to implement dynamic loading for mac as well. Hopefully shortly.

**Comment by tiepettersen** [comment] 2020-01-15 11:12
Ahh, sneaky! Let me know if you would like some help testing out a possible macos fix.

**Comment by astonbitecode** [comment] 2020-01-15 12:06
Thanks, I appreciate it.

I will use this issue to commit the dynamic loading impl for mac. It would be great if you tested it using the master branch!

**Comment by astonbitecode** [comment] 2020-01-15 14:21
I deleted macos specific code, hoping that it would "just work", but I see the [travis build for macos](https://travis-ci.org/astonbitecode/j4rs/jobs/637448453) fails. 

> DEBUG: Creating a Jvm
> thread 'api::api_unit_tests::invocation_into_primitive' panicked at 'Could not load the jvm dynamic library: Custom { kind: Other, error: "dlopen(/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home/lib/server/libjvm.so, 2): image not found" }', src/libcore/result.rs:1165:5

I use `export JAVA_HOME="$(/usr/libexec/java_home)"` in .travis.yml to set the JAVA_HOME, however it seems that the libjvm.so is not found. If you have a mac, can you have a closer look on what may go wrong? Is the path of `JAVA_HOME` correct? Is the .so indeed missing?

**Comment by tiepettersen** [comment] 2020-01-15 15:07
On the mac machine I have available, `java_home` returns as follows:

```bash
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
```

and I find the `libjvm` under `java_home` here:

```bash
$ find $(/usr/libexec/java_home) | grep libjvm
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/server/libjvm.dylib
```

**Comment by tiepettersen** [comment] 2020-01-16 12:29
I tried out the master branch, and I was able to compile for macos. Running the executable gave me the following J4RS error:

```
A J4Rs error has occured: Error { kind: NotFound, message: "entity not found" }
```

**Comment by tiepettersen** [comment] 2020-01-17 09:23
To be more specific, the error results from `JvmBuilder::build()` with the following error: 

```
GeneralError("Error { kind: NotFound, message: \"entity not found\" }")
```

**Comment by tiepettersen** [comment] 2020-01-17 15:21
It seems to me the issue is that j4rs is assuming dynamic libraries on macos is `*.so`, however, they are `*.dylib`.

**Comment by astonbitecode** [comment] 2020-01-17 23:45
You are right! The issue is in the java-locator crate. 

I will release a patch for it next week. If you want, however, you can use the j4rs 0.11.0 release from the crates.io and define and export the `LD_LIBRARY_PATH`. The fact that in that version j4rs statically links to jvm when on macos will make your program compile and run with no issues I guess, as long as you have exported this env var before.

Once again, thanks for the report and the help.

**Comment by astonbitecode** [comment] 2020-01-20 08:04
Ok, I have made a patch for it. The [macos tests pass in Travis](https://travis-ci.org/astonbitecode/j4rs/builds/639365113). Before releasing, could you please see if it is working for you too? 

Just make sure you perform `cargo update` before building because the issue fixed is in a dependency of j4rs.

**Comment by astonbitecode** [comment] 2020-01-27 10:29
Any news @tiepettersen ? I think we could close this...

**Comment by tiepettersen** [comment] 2020-01-27 15:26
@astonbitecode, sorry, haven't had the time to test it yet. Will try it now.

**Comment by astonbitecode** [comment] 2020-02-24 09:19
I guess this can be closed by now...

**Closed by astonbitecode** 2020-02-24 09:19 UTC
