### ISSUE TITLE
Workaround when `dlopen` is disabled?

### ISSUE THREAD

**Issue by wangxiaoying** [astonbitecode/j4rs#55] opened 2023-04-20 18:31 UTC
I'm exposing my rust library to a cpp project through some APIs, which disables `dlopen` for safety reasons. One of the API would use `j4rs` to invoke a jar file, and lead to crash at `Library::new` in `generic.rs` when loading `libjvm.so`, with following error message:

```
thread '<unnamed>' panicked at 'Could not load the jvm dynamic library: DlOpen { desc: "ClickHouse does not allow dynamic library loading" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/j4rs-0.15.3/src/api_tweaks/generic.rs:46:49
```

I am not very familiar with dynamic loading. Is there any workaround for it? Thank you!

**Comment by astonbitecode** [comment] 2023-04-21 08:02
JNI needs the `libjvm` dynamic library and `j4rs` loads it upon startup using the `libloading` crate.
`libjvm` is part of a JVM installed in a system and is located using the `java_locator` crate.

An alternative to the behavior above, could be that the `libjvm` is given as input via `LD_LIBRARY_PATH` or similar. Unfortunately, this is not currently supported.

We could, however, implement a feature and when some user opts-in for it, `j4rs` could use any predefined linker variables like `LD_LIBRARY_PATH` to load `libjvm`.

How does this sound? Would that be an adequate solution? I am not familiar with ClickHouse, so I cannot say whether it would be enough, but IMO it could worth a try.

**Comment by wangxiaoying** [comment] 2023-04-21 16:39
Hi @astonbitecode , thanks for the quick reply!

> We could, however, implement a feature and when some user opts-in for it, j4rs could use any predefined linker variables like LD_LIBRARY_PATH to load libjvm.

I don't have any experience in this, so I'm not sure whether I missed anything. But as far as I see, ClickHouse forbids `dlopen` by [implementing a function trap of if](https://github.com/ClickHouse/ClickHouse/pull/41429/files). And also it allows dynamic link, which is how I integrate my library with it. So I think this solution worth a try and probably would work.

I can help testing on this, and please also let me know if there is other things that I can do. Thanks a lot!

**Comment by astonbitecode** [comment] 2023-04-24 12:35
So, I implemented a new feature called `no-runtime-libloading`. If you enable it, defining the `j4rs` dependency as following:

`j4rs = { git = "https://github.com/astonbitecode/j4rs.git", features = ["no-runtime-libloading"] }` 

the runtime dynamic library loading will not take place and the `jvm` dynamic library must be defined by other means. 

For example, you should be able to build your application like:

` RUSTFLAGS='-L /usr/lib/jvm/java-17-openjdk-amd64/lib/server' cargo build`

and run it:

`LD_LIBRARY_PATH=/usr/lib/jvm/java-17-openjdk-amd64/lib/server ./target/debug/my_lib_that_uses_j4rs`

Can you please give this a try?

**Comment by wangxiaoying** [comment] 2023-04-24 17:34
Hi @astonbitecode , thanks for the new feature!

I tried to follow the above instruction but got error when initializing jvm:

```
Error occurred during initialization of VM
Unable to load jimage library: /usr/lib/jvm/zulu-17-amd64/lib/libjimage.so
```

Basically adding the `RUSTFLAGS='-L ${JAVA_HOME}/lib/server`, my library is built like:
```
ldd target/debug/libconnectorx_cpp.so
        linux-vdso.so.1 (0x00007ffc327fe000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2a59eb6000)
        libjvm.so => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2a59c9e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2a59a96000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2a59877000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a594d9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2a592d5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a58ee4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2a5c7e2000)
```

And the clickhouse binary is built like this:
```
ldd build_vscode/programs/clickhouse
        linux-vdso.so.1 (0x00007ffcb81e8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc3a7873000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc3a766b000)
        libjvm.so => /usr/lib/jvm/zulu-17-amd64/lib/server/libjvm.so (0x00007fc3a62e5000)
        /root/connector-x/target/debug/libconnectorx_cpp.so (0x00007fc3a3bd6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc3a39b7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3a35c6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc3a7a77000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc3a3228000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc3a300b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc3a2df3000)
```

I started clickhouse in root user, and cannot use gdb to catch any error since the program exit directly after the error. I'm not sure how to dump more information about this. Please let me know if you want me to try or do anything from my side. Thank you!

**Comment by astonbitecode** [comment] 2023-04-25 08:10
I cannot say who needs `libjimage.so`... It is not mentioned in the ldd output you provided and as far as I can tell, `libjvm.so` does not need it either:

```
ldd /usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so

	linux-vdso.so.1 (0x00007ffdcfd3a000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6689e3a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6689d53000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6689b2b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f668b41f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6689b0b000)
```

Maybe the Java code needs it and tries to load it? If this is the case, there is the possibility that the `LD_LIBRARY_PATH` got messed up, which is one of the reasons its usage should be avoided. I would either:

* Define LD_LIBRARY_PATH like:
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-17-openjdk-amd64/lib/server
```
OR

* Use `rpath` during building:
```
RUSTFLAGS='-L /usr/lib/jvm/java-17-openjdk-amd64/lib/server -C link-args=-Wl,-rpath,/usr/lib/jvm/java-17-openjdk-amd64/lib/server' cargo build
```
This way, there is no need to set the LD_LIBRARY_PATH (and it is better IMHO)

**Comment by astonbitecode** [comment] 2023-04-25 23:12
Well, you could expirement:

* If the library is needed by the native code, maybe adding the lib path to the LD_LIBRARY_PATH could help
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-17-openjdk-amd64/lib/server:/usr/lib/jvm/java-17-openjdk-amd64/lib
```

* If needed from the JVM, you could [add the lib location to the VM options](https://docs.rs/j4rs/0.15.3/j4rs/struct.JvmBuilder.html#method.java_opt)
```rust
JavaOpt::new("-Djava.library.path=/usr/lib/jvm/java-17-openjdk-amd64/lib")
```

None of the above seem logical though. The lib directory is in the JDK so, if needed by the Java code it should be there (the JVM is created successfully in your last comments). From the other hand, if needed from the native code we should see it in the ldd output somehow.

Maybe you could give it a try using openjdk too.

Is there some code you could provide to try reproducing? As far as I can tell in some POC, `j4rs` starts successfully with the new feature...

**Comment by wangxiaoying** [comment] 2023-04-26 17:49
I tested on openjdk and got the same error message that saying `libjimage.so` cannot be load although it is there:
```
Error occurred during initialization of VM
Unable to load jimage library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libjimage.so

ll /usr/lib/jvm/java-17-openjdk-amd64/lib/libjimage.so
-rw-r--r-- 1 root root 22560 Jan 20 16:56 /usr/lib/jvm/java-17-openjdk-amd64/lib/libjimage.so
```

I will try to make a reproducible toy example maybe later this weekend. Thank you!

**Comment by wangxiaoying** [comment] 2023-04-28 23:59
Hi @astonbitecode , I found that the error goes away when it is invoked by a new project instead of clickhouse. So I guess it is related to some setups/code in clickhouse.

Here is a toy example that the error can be reproduced, it includes building clickhouse locally (sorry for the inconvinience):

#### Build cpp library (I reused a previous toy example)

1. `git clone git@github.com:wangxiaoying/j4rs-sanitizer-example.git`
2. `cd j4rs-sanitizer-example`
3. `RUSTFLAGS='-L ${JAVA_HOME}/lib/server' cargo build`
4. `cd ..`

#### Build clickhouse that invoke the method `j4rs_test` from `j4rs-sanitizer-example`

Basically following [this official](https://clickhouse.com/docs/en/development/developer-instruction#cloning-a-repository-to-your-development-machine). This requires [ninja-build and clang >=15](https://clickhouse.com/docs/en/development/developer-instruction#build-system)

1. `git clone --shallow-submodules git@github.com:wangxiaoying/ClickHouse.git`
2. `cd ClickHouse`
4. `git checkout j4rs`
5. change the `libjvm.so` path in `./contrib/cxtest-cmake/CMakeLists.txt` to your local path
6. `git submodule init`
7. `git submodule update` - this may take a while
8. `mkdir build && cd build`
9. `export CC=clang CXX=clang++`
10. `cmake -DCMAKE_BUILD_TYPE=Debug ..`
11. `ninja clickhouse-server clickhouse-client` - this may take a while

#### Start clickhouse server
`./build/program/clickhouse server`

#### Trigger the error
`./build/program/clickhouse/client`

The start of the client will make the server invoke `j4rs_test` in `src/Server/TCPHandler.cpp`, which's header file is located at `contrib/cxtest` and the implementation is in `j4rs-sanitizer-example`.

**Comment by astonbitecode** [comment] 2023-05-03 06:17
Hi @wangxiaoying, I tried to reproduce the error using the steps above, but I get something else...

>2023.05.03 06:05:02.314466 [ 5780 ] {} <Debug> TCPHandler: original query: SELECT * FROM viewIfPermitted(SELECT message FROM system.warnings ELSE null('message String'))
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GeneralError("Error { kind: NotFound, message: \"No such file or directory (os error 2)\" }")', src/run_java.rs:8:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
2023.05.03 06:05:02.315549 [ 5779 ] {} <Trace> BaseDaemon: Received signal 6
2023.05.03 06:05:02.316153 [ 6029 ] {} <Fatal> BaseDaemon: ########################################
2023.05.03 06:05:02.316374 [ 6029 ] {} <Fatal> BaseDaemon: (version 23.3.1.2537, build id: F506F1CDA837C7328D571098239EB1B61F5AB478) (from thread 5780) (no query) Received signal Aborted (6)
2023.05.03 06:05:02.316550 [ 6029 ] {} <Fatal> BaseDaemon: 
2023.05.03 06:05:02.316813 [ 6029 ] {} <Fatal> BaseDaemon: Stack trace: 0x7efcb68d4ce1 0x7efcb68be537 0x7efcb6b4b257 0x7efcb6b48523 0x7efcb6b53d23 0x358de288 0x2c662451 0x2c673a25 0x31aa2ab9 0x31aa32fc 0x31cf38f4 0x31cf069a 0x31cef39e 0x7efcb6a79ea7 0x7efcb6997a2f
2023.05.03 06:05:02.317096 [ 6029 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x38ce1 in /lib/x86_64-linux-gnu/libc-2.31.so
2023.05.03 06:05:02.317259 [ 6029 ] {} <Fatal> BaseDaemon: 5. abort @ 0x22537 in /lib/x86_64-linux-gnu/libc-2.31.so
2023.05.03 06:05:02.596345 [ 6029 ] {} <Fatal> BaseDaemon: 6. /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/mod.rs:350: std::sys::unix::abort_internal::heb27eacee66fb84f @ 0xb7257 in /j4rs/j4rs-sanitizer-example/target/debug/libj4rs_sanitizer_example.so
2023.05.03 06:05:02.872784 [ 6029 ] {} <Fatal> BaseDaemon: 7. /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:63: __rust_drop_panic @ 0xb4523 in /j4rs/j4rs-sanitizer-example/target/debug/libj4rs_sanitizer_example.so
2023.05.03 06:05:02.873653 [ 6029 ] {} <Fatal> BaseDaemon: 8. /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/panic_unwind/src/gcc.rs:80: panic_unwind::real_imp::panic::exception_cleanup::h9e3dbea03d35efa0 @ 0xbfd23 in /j4rs/j4rs-sanitizer-example/target/debug/libj4rs_sanitizer_example.so
2023.05.03 06:05:02.900045 [ 6029 ] {} <Fatal> BaseDaemon: 9. /j4rs/ClickHouse/contrib/llvm-project/libcxxabi/src/cxa_exception.cpp:571: __cxa_end_catch @ 0x358de288 in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:03.003368 [ 6021 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.05 GiB, peak 1.05 GiB, free memory in arenas 5.17 MiB, will set to 1.20 GiB (RSS), difference: 149.89 MiB
2023.05.03 06:05:03.358337 [ 6029 ] {} <Fatal> BaseDaemon: 10. /j4rs/ClickHouse/src/Server/TCPHandler.cpp:571: DB::TCPHandler::runImpl() @ 0x2c662451 in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:03.848903 [ 6029 ] {} <Fatal> BaseDaemon: 11. /j4rs/ClickHouse/src/Server/TCPHandler.cpp:2041: DB::TCPHandler::run() @ 0x2c673a25 in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:03.879375 [ 6029 ] {} <Fatal> BaseDaemon: 12. /j4rs/ClickHouse/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x31aa2ab9 in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:03.920276 [ 6029 ] {} <Fatal> BaseDaemon: 13. /j4rs/ClickHouse/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x31aa32fc in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:03.967794 [ 6029 ] {} <Fatal> BaseDaemon: 14. /j4rs/ClickHouse/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x31cf38f4 in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:04.003317 [ 6021 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.20 GiB, peak 1.20 GiB, free memory in arenas 5.30 MiB, will set to 1.26 GiB (RSS), difference: 59.64 MiB
2023.05.03 06:05:04.019281 [ 6029 ] {} <Fatal> BaseDaemon: 15. /j4rs/ClickHouse/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x31cf069a in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:04.061867 [ 6029 ] {} <Fatal> BaseDaemon: 16. /j4rs/ClickHouse/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x31cef39e in /j4rs/ClickHouse/build/programs/clickhouse
2023.05.03 06:05:04.062153 [ 6029 ] {} <Fatal> BaseDaemon: 17. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
2023.05.03 06:05:04.062321 [ 6029 ] {} <Fatal> BaseDaemon: 18. clone @ 0xfba2f in /lib/x86_64-linux-gnu/libc-2.31.so
2023.05.03 06:05:04.062501 [ 6029 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.05.03 06:05:04.062667 [ 6029 ] {} <Information> SentryWriter: Not sending crash report
Aborted (core dumped)


Apparently something else went wrong in my case...

However, I see the ldd output for the produced `libj4rs_sanitizer_example.so` shows 

`libjvm.so => not found`

Does that mean that the Clickhouse server should be further configured during runtime to locate the `libjvm.so`? Or the `set_property(TARGET ch_contrib::jvm PROPERTY IMPORTED_LOCATION "/usr/lib/jvm/zulu-17-amd64/lib/server/libjvm.so")` does this?

Would it worth trying building your library using `rpath`?

```
RUSTFLAGS='-L /usr/lib/jvm/java-17-openjdk-amd64/lib/server -C link-args=-Wl,-rpath,/usr/lib/jvm/java-17-openjdk-amd64/lib/server' cargo build
```

**Comment by wangxiaoying** [comment] 2023-05-04 04:01
Thanks for trying to reproduce the error!

For the `no such file or directory` error, can you try whether setting up the environment variable `J4RS_BASE_PATH` be the path of your local `jasset` directory when starting the clickhouse server will resolve the issue? It will be used in `with_base_path` when initializing the jvm [here](https://github.com/wangxiaoying/j4rs-sanitizer-example/blob/main/src/run_java.rs#L8). Sorry that I forgot to mention this previously.

> Would it worth trying building your library using rpath?

I tried it previously but it result in the same `libjimage` error. I think `libjvm.so => not found` should be fine here since it is linked to the `./build/program/clickhouse` binary.

**Comment by astonbitecode** [comment] 2023-05-05 07:58
Thanks, I am now able to reproduce it.

---

One - aside - note regarding your `j4rs` implementation, is that when you create the [JvmBuilder](https://github.com/wangxiaoying/j4rs-sanitizer-example/blob/49d30d4473ac158020e0b8af5c33b2e477d39ad3/src/run_java.rs#L8) you may as well not use `skip_setting_native_lib`, because you are anyhow setting the correct path using `with_base_path`. This line can be like:

```rust
JvmBuilder::new().with_base_path(j4rs_base.as_str()).build().unwrap()
```
This way you are also able to use Java callbacks if you need.

---

Back to the issue, I really cannot say how `jimage` is getting into the story. 
Having debug logging enabled for j4rs with `export J4RS_CONSOLE_LOG_LEVEL=debug`, it is visible that the error happens when the JVM is being created:

>INFO: Setting classpath to -Djava.class.path=/j4rs/j4rs-sanitizer-example/target/debug/jassets/j4rs-0.15.4-SNAPSHOT-jar-with-dependencies.jar
INFO: Setting library path to -Djava.library.path=/j4rs/j4rs-sanitizer-example/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-44776f87ea042a3c
DEBUG: Creating a Jvm
INFO: No JVMs exist. Creating a new one...
Error occurred during initialization of VM
Unable to load jimage library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libjimage.so

However, the error seems to happen pretty early. I tried setting the `Xlog` VM Option in order to print which JNI libraries are actually loaded from Java, but there are no logs at all for it.

I also tried to use the `j4rs-sanitizer-example` in a normal test application, using the `Xlog` option and the output retrieved did not contain the `libjimage`:

>[0.021s][info][library] Loaded library libjsvml.so, handle 0x000056287c53fbe0
[0.087s][info][library] Loaded library /usr/lib/jvm/java-17-openjdk-amd64/lib/libnio.so, handle 0x000056287c634d90
[0.101s][info][library] Loaded library /usr/lib/jvm/java-17-openjdk-amd64/lib/libzip.so, handle 0x000056287c3ec390
[0.169s][info][library] Loaded library /j4rs/j4rs-sanitizer-example/target/debug/deps/libj4rs.so, handle 0x000056287c6be000

Have you tried running a java application from inside Clickhouse? Is it even possible to run Java in Clickhouse? If yes, you could try running a normal Java application in Clickhouse, having set `-Xlog:library=info` and see if libjimage is loaded somehow...

**Comment by wangxiaoying** [comment] 2023-05-05 17:41
Thanks for the hints on `skip_setting_native_lib`, will update this in my code.

> Have you tried running a java application from inside Clickhouse? Is it even possible to run Java in Clickhouse?

Actually I don't have any experience in this. I did find some java code under the `contrib/` directory but I have no idea how they works inside clickhouse (or whether they are actually used).

Anyway since we can run this outside of clickhouse, I do think it should be something related to the setup of clickhouse instead of implementation of `j4rs`. Please feel free to close this issue. Also thanks a lot for the helping and everything!

**Comment by astonbitecode** [comment] 2023-05-05 20:23
Ok, so let's close this and please, feel free to reopen or open a new issue if something newer pops up and `j4rs` can help. 

Of course, the `no-runtime-libloading` feature will not be rolled back. I hope that finally, you, or someone else will find it useful.

Thanks!

**Closed by astonbitecode** 2023-05-05 20:23 UTC
